# Generated by Django 3.1.3 on 2020-11-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100)),
                ('Komentar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=1000)),
                ('deskripsi', models.TextField(max_length=3000)),
                ('Category', models.CharField(choices=[('Gitar Akustik', 'Gitar Akustik'), ('Gitar Elektrik', 'Gitar Elektrik'), ('Gitar Classic', 'Gitar Classic')], max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='static/%y')),
                ('button', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=2000)),
                ('Tags', models.ManyToManyField(to='myaccount.Tag')),
            ],
        ),
    ]
