# Generated by Django 3.1.3 on 2020-11-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_auto_20201127_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='des',
            field=models.TextField(max_length=5000),
        ),
    ]
