# Generated by Django 3.1.2 on 2020-10-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Tags',
            field=models.ManyToManyField(to='myaccount.Tag'),
        ),
    ]
