# Generated by Django 3.1.2 on 2020-10-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0005_komentar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Komentar',
        ),
    ]
