# Generated by Django 3.1.2 on 2020-10-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0006_auto_20201026_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Category',
            field=models.CharField(choices=[('Gitar Akustik', 'Gitar Akustik'), ('Gitar Elektrik', 'Gitar Elektrik'), ('Gitar Classic', 'Gitar Classic')], max_length=1000, null=True),
        ),
    ]
