# Generated by Django 3.1.2 on 2020-11-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0008_auto_20201028_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='button',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='deskripsi',
            field=models.CharField(max_length=10000000000000),
        ),
    ]
