# Generated by Django 3.1.2 on 2020-11-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0009_auto_20201106_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='des',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
